### ISSUE TITLE
 string indices must be integers

### ISSUE THREAD

**Issue by JinYu1998** [AgentEra/Agently-Daily-News-Collector#14]
```
python app.py

[Please input the topic of your daily news collection]: education
2024-06-16 22:38:59,865 [INFO]  [Outline Generated]     {'report_title': 'Latest Education News', 'column_list': [{'column_title': 'Policy and Legislation', 'column_requirement': 'All news articles in this column should focus on new policies, legislation, and regulations related to education. Ensure the content is up-to-date and relevant to current educational policies.', 'search_keywords': 'education policy legislation government school college'}, {'column_title': 'Innovations in Education', 'column_requirement': 'This column should cover innovative approaches, technologies, and methodologies in the field of education. Articles should highlight advancements and new trends in teaching and learning.', 'search_keywords': 'education innovation technology learning teaching'}, {'column_title': 'Educational Events and Research', 'column_requirement': 'News articles in this column should focus on academic events, research findings, and scholarly developments in education. Ensure the content is based on reliable sources and academic institutions.', 'search_keywords': 'education event research academic study'}]}
2024-06-16 22:39:04,871 [INFO]  [Start Generate Column] Policy and Legislation
2024-06-16 22:39:06,666 [INFO]  [Search News Count]     8
2024-06-16 22:39:14,922 - ERROR - Node Execution Exception: 'pick_news'(3cd59ad5-8449-4d6b-83fe-a0477234c796) string indices must be integers
2024-06-16 22:39:14,923 - ERROR - Node Execution Exception: 'generate_columns'(100c38c1-c72d-4b0e-83b3-5d298b85907a) string indices must be integers
Traceback (most recent call last):
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(deps_dict, self.store)
  File "Agently-Daily-News-Collector/workflows/column_workflow.py", line 53, in pick_news_executor
    if pick_result["can_use"]:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(deps_dict, self.store)
  File "Agently-Daily-News-Collector/workflows/main_workflow.py", line 58, in generate_columns_executor
    column_data = start_column_workflow(
  File "Agently-Daily-News-Collector/workflows/column_workflow.py", line 152, in start
    column_workflow.start()
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 67, in start
    self.executor.start(runtime_data)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
    self._execute_main(entries)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
    self._execute_partial(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
    child_executed = self._execute_single_chunk(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
    self._execute_single_chunk_core(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
    exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Agently-Daily-News-Collector/app.py", line 21, in <module>
    main_workflow.start(
  File "Agently-Daily-News-Collector/workflows/main_workflow.py", line 109, in start
    main_workflow.start()
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 67, in start
    self.executor.start(runtime_data)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
    self._execute_main(entries)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
    self._execute_partial(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
    child_executed = self._execute_single_chunk(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
    self._execute_single_chunk_core(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
    exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: string indices must be integers
```

**Comment by Maplemx** [comment]
Hi, you can turn on the debug mode by set IS_DEBUG to true in SETTINGS.yaml file to observe model generation process to see what's wrong when generating pick news chunk.

I'll try to look into this issue too.

**Comment by JinYu1998** [comment]
> Hi, you can turn on the debug mode by set IS_DEBUG to true in SETTINGS.yaml file to observe model generation process to see what's wrong when generating pick news chunk.您好，您可以通过在 SETTINGS.yaml 文件中将 IS_DEBUG 设置为 true 来打开调试模式，观察模型生成过程，看看生成pick news chunk 时出了什么问题。
> 
> I'll try to look into this issue too.我也会尝试研究一下这个问题。

Hi, I have set IS_DEBUG to true in the SETTINGS.yaml file. Here is the full output from the console.

```python
 python app.py

[Please input the topic of your daily news collection]: education
[Request Data]
 {
    "stream": true,
    "messages": [
        {
            "role": "user",
            "content": "# [INPUT]:\neducation\n\n# [INSTRUCTION]:\ntask: prepare news collection outline according {input}'s topic\noutput language: English\n\n\n# [OUTPUT REQUIREMENT]:\n## TYPE:\nJSON can be parsed in Python\n## FORMAT:\n{\n\t\"report_title\": <str>,//generate a title for this news collection like \"daily news about sports\", \"today's news about finance\"\n\t\"column_list\": \n\n\t\t[\n\t\t\t\n\t\t\t{\n\t\t\t\t\"column_title\": <str>,//None\n\t\t\t\t\"column_requirement\": <str>,//describe recheck standard about the contents in this column to make sure all contents are aimed at the requirement of {input}'s topic\n\t\t\t\t\"search_keywords\": <str>,//search keywords for this column splited by space. make sure the filed keyword about {input} is included in keywords.\n\t\t\t\t},,\n\t\t\t\\\\...\n\t\t],,//the number of columns <= 3\n}\n\n\n[OUTPUT]:\n"
        }
    ],
    "model": "gpt-35-turbo",
    "temperature": 0.75
}
[Realtime Response]

[Request] OpenAI Error: {'id': '', 'choices': [], 'created': 0, 'model': '', 'object': '', 'system_fingerprint': None, 'usage': None, 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}]}
{
        "report_title": "Latest Updates on Education",
        "column_list": 
                [
                        {
                                "column_title": "Education Policies",
                                "column_requirement": "All contents must be related to recent education policies, reforms, and updates.",
                                "search_keywords": "education policies reforms updates government school college university"
                        },
                        {
                                "column_title": "Education Technology",
                                "column_requirement": "Focus on the latest advancements in educational technology, online learning, and digital resources.",
                                "search_keywords": "education technology online learning digital resources edtech"
                        },
                        {
                                "column_title": "Education Research",
                                "column_requirement": "Articles and studies on educational research, trends, and innovations.",
                                "search_keywords": "education research trends innovations studies"
                        }
                ]
}
--------------------------

[Final Reply]
 {
        "report_title": "Latest Updates on Education",
        "column_list": 
                [
                        {
                                "column_title": "Education Policies",
                                "column_requirement": "All contents must be related to recent education policies, reforms, and updates.",
                                "search_keywords": "education policies reforms updates government school college university"
                        },
                        {
                                "column_title": "Education Technology",
                                "column_requirement": "Focus on the latest advancements in educational technology, online learning, and digital resources.",
                                "search_keywords": "education technology online learning digital resources edtech"
                        },
                        {
                                "column_title": "Education Research",
                                "column_requirement": "Articles and studies on educational research, trends, and innovations.",
                                "search_keywords": "education research trends innovations studies"
                        }
                ]
} 
--------------------------

[Cleaned JSON String]:
 {
        "report_title": "Latest Updates on Education",
        "column_list": 
                [
                        {
                                "column_title": "Education Policies",
                                "column_requirement": "All contents must be related to recent education policies, reforms, and updates.",
                                "search_keywords": "education policies reforms updates government school college university"
                        },
                        {
                                "column_title": "Education Technology",
                                "column_requirement": "Focus on the latest advancements in educational technology, online learning, and digital resources.",
                                "search_keywords": "education technology online learning digital resources edtech"
                        },
                        {
                                "column_title": "Education Research",
                                "column_requirement": "Articles and studies on educational research, trends, and innovations.",
                                "search_keywords": "education research trends innovations studies"
                        }
                ]
}

--------------------------

2024-06-17 14:40:06,949 [INFO]  [Outline Generated]     {'report_title': 'Latest Updates on Education', 'column_list': [{'column_title': 'Education Policies', 'column_requirement': 'All contents must be related to recent education policies, reforms, and updates.', 'search_keywords': 'education policies reforms updates government school college university'}, {'column_title': 'Education Technology', 'column_requirement': 'Focus on the latest advancements in educational technology, online learning, and digital resources.', 'search_keywords': 'education technology online learning digital resources edtech'}, {'column_title': 'Education Research', 'column_requirement': 'Articles and studies on educational research, trends, and innovations.', 'search_keywords': 'education research trends innovations studies'}]}
2024-06-17 14:40:11,955 [INFO]  [Start Generate Column] Education Policies
2024-06-17 14:40:13,016 [INFO]  [Search News Count]     3
[Request Data]
 {
    "stream": true,
    "messages": [
        {
            "role": "user",
            "content": "# [INPUT]:\n[{'id': 0, 'title': 'Malemu Saulos Chilima was part of the university team in support of the transition says Chikosa Silungwe', 'brief': 'Malemu Saulos Chilima \\xa0was part of the university team in support of the transition \\xa0says\\xa0 Chikosa Silungwe - The Maravi Post', 'url': 'https://www.maravipost.com/malemu-saulos-chilima-was-part-of-the-university-team-in-support-of-the-transition-says-chikosa-silungwe/', 'source': 'The Maravi Post', 'date': '2024-06-16T12:00:00+00:00'}, {'id': 1, 'title': 'Colleges and Schools at Purdue', 'brief': 'The Colleges and Schools at Purdue University have been dedicated to preparing students for a competitive job market. Please look through our academic catalog below to find the program that will help meet your career and life goals.', 'url': 'https://www.purdue.edu/home/colleges_schools/', 'source': 'Purdue University', 'date': '2024-06-16T06:52:00+00:00'}, {'id': 2, 'title': 'Malawi Catholic Church Criticizes Leadership Over Delayed Response to VP Saulos Chilima Plane Crash Rescue', 'brief': 'Malawi Catholic Church Criticizes Leadership Over Delayed Response to VP Saulos Chilima Plane Crash Rescue - The Maravi Post', 'url': 'https://www.maravipost.com/malawi-catholic-church-criticizes-leadership-over-delayed-response-to-vp-saulos-chilima-plane-crash-rescue/', 'source': 'The Maravi Post', 'date': '2024-06-16T17:31:00+00:00'}]\n\n# [INSTRUCTION]:\nnews select rules:\n- All contents must be related to recent education policies, reforms, and updates.\n- if several news are similar, just retain the one with most famous source and output\n  {can_use} as false for others\n\n\n# [OUTPUT REQUIREMENT]:\n## TYPE:\nJSON can be parsed in Python\n## FORMAT:\n[\n\t\n\t{\n\t\t\"id\": <int>,//value from {input.[].id}\n\t\t\"can_use\": <bool>,//judge if {input.brief} can be used according {instruct}\n\t\t\"recommend_comment\": <str>,//provide your recommend comment if {can_use} == true, or just output null\n\t\t},,\n\t\\\\...\n]\n\n\n[OUTPUT]:\n"
        }
    ],
    "model": "gpt-35-turbo",
    "temperature": 0.75
}
[Realtime Response]

[Request] OpenAI Error: {'id': '', 'choices': [], 'created': 0, 'model': '', 'object': '', 'system_fingerprint': None, 'usage': None, 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}]}

{
        "id": 0,
        "can_use": false,
        "recommend_comment": null
}


--------------------------

[Final Reply]
 
{
        "id": 0,
        "can_use": false,
        "recommend_comment": null
}

         
--------------------------

[Cleaned JSON String]:
 {
        "id": 0,
        "can_use": false,
        "recommend_comment": null
}

--------------------------

2024-06-17 14:40:20,449 - ERROR - Node Execution Exception: 'pick_news'(aa01827e-c3a4-4ace-9f9a-a9eb21b88133) string indices must be integers
2024-06-17 14:40:20,449 - ERROR - Node Execution Exception: 'generate_columns'(ab330942-ae88-4a79-a30c-c481602679b1) string indices must be integers
Traceback (most recent call last):
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(deps_dict, self.store)
  File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/column_workflow.py", line 54, in pick_news_executor
    if pick_result["can_use"]:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
    exec_res = chunk_executor(deps_dict, self.store)
  File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/main_workflow.py", line 58, in generate_columns_executor
    column_data = start_column_workflow(
  File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/column_workflow.py", line 153, in start
    column_workflow.start()
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 67, in start
    self.executor.start(runtime_data)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
    self._execute_main(entries)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
    self._execute_partial(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
    child_executed = self._execute_single_chunk(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
    self._execute_single_chunk_core(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
    exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/app.py", line 21, in <module>
    main_workflow.start(
  File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/main_workflow.py", line 109, in start
    main_workflow.start()
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 67, in start
    self.executor.start(runtime_data)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
    self._execute_main(entries)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
    self._execute_partial(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
    child_executed = self._execute_single_chunk(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
    self._execute_single_chunk_core(
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
    exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
  File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
    raise Exception(e)
Exception: string indices must be integers
```

**Comment by JinYu1998** [comment]
> > Hi, you can turn on the debug mode by set IS_DEBUG to true in SETTINGS.yaml file to observe model generation process to see what's wrong when generating pick news chunk.您好，您可以通过在 SETTINGS.yaml 文件中将 IS_DEBUG 设置为 true 来打开调试模式，观察模型生成过程，看看生成pick news chunk 时出了什么问题。
> > I'll try to look into this issue too.我也会尝试研究一下这个问题。
> 
> Hi, I have set IS_DEBUG to true in the SETTINGS.yaml file. Here is the full output from the console.
> 
> ```python
>  python app.py
> 
> [Please input the topic of your daily news collection]: education
> [Request Data]
>  {
>     "stream": true,
>     "messages": [
>         {
>             "role": "user",
>             "content": "# [INPUT]:\neducation\n\n# [INSTRUCTION]:\ntask: prepare news collection outline according {input}'s topic\noutput language: English\n\n\n# [OUTPUT REQUIREMENT]:\n## TYPE:\nJSON can be parsed in Python\n## FORMAT:\n{\n\t\"report_title\": <str>,//generate a title for this news collection like \"daily news about sports\", \"today's news about finance\"\n\t\"column_list\": \n\n\t\t[\n\t\t\t\n\t\t\t{\n\t\t\t\t\"column_title\": <str>,//None\n\t\t\t\t\"column_requirement\": <str>,//describe recheck standard about the contents in this column to make sure all contents are aimed at the requirement of {input}'s topic\n\t\t\t\t\"search_keywords\": <str>,//search keywords for this column splited by space. make sure the filed keyword about {input} is included in keywords.\n\t\t\t\t},,\n\t\t\t\\\\...\n\t\t],,//the number of columns <= 3\n}\n\n\n[OUTPUT]:\n"
>         }
>     ],
>     "model": "gpt-35-turbo",
>     "temperature": 0.75
> }
> [Realtime Response]
> 
> [Request] OpenAI Error: {'id': '', 'choices': [], 'created': 0, 'model': '', 'object': '', 'system_fingerprint': None, 'usage': None, 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}]}
> {
>         "report_title": "Latest Updates on Education",
>         "column_list": 
>                 [
>                         {
>                                 "column_title": "Education Policies",
>                                 "column_requirement": "All contents must be related to recent education policies, reforms, and updates.",
>                                 "search_keywords": "education policies reforms updates government school college university"
>                         },
>                         {
>                                 "column_title": "Education Technology",
>                                 "column_requirement": "Focus on the latest advancements in educational technology, online learning, and digital resources.",
>                                 "search_keywords": "education technology online learning digital resources edtech"
>                         },
>                         {
>                                 "column_title": "Education Research",
>                                 "column_requirement": "Articles and studies on educational research, trends, and innovations.",
>                                 "search_keywords": "education research trends innovations studies"
>                         }
>                 ]
> }
> --------------------------
> 
> [Final Reply]
>  {
>         "report_title": "Latest Updates on Education",
>         "column_list": 
>                 [
>                         {
>                                 "column_title": "Education Policies",
>                                 "column_requirement": "All contents must be related to recent education policies, reforms, and updates.",
>                                 "search_keywords": "education policies reforms updates government school college university"
>                         },
>                         {
>                                 "column_title": "Education Technology",
>                                 "column_requirement": "Focus on the latest advancements in educational technology, online learning, and digital resources.",
>                                 "search_keywords": "education technology online learning digital resources edtech"
>                         },
>                         {
>                                 "column_title": "Education Research",
>                                 "column_requirement": "Articles and studies on educational research, trends, and innovations.",
>                                 "search_keywords": "education research trends innovations studies"
>                         }
>                 ]
> } 
> --------------------------
> 
> [Cleaned JSON String]:
>  {
>         "report_title": "Latest Updates on Education",
>         "column_list": 
>                 [
>                         {
>                                 "column_title": "Education Policies",
>                                 "column_requirement": "All contents must be related to recent education policies, reforms, and updates.",
>                                 "search_keywords": "education policies reforms updates government school college university"
>                         },
>                         {
>                                 "column_title": "Education Technology",
>                                 "column_requirement": "Focus on the latest advancements in educational technology, online learning, and digital resources.",
>                                 "search_keywords": "education technology online learning digital resources edtech"
>                         },
>                         {
>                                 "column_title": "Education Research",
>                                 "column_requirement": "Articles and studies on educational research, trends, and innovations.",
>                                 "search_keywords": "education research trends innovations studies"
>                         }
>                 ]
> }
> 
> --------------------------
> 
> 2024-06-17 14:40:06,949 [INFO]  [Outline Generated]     {'report_title': 'Latest Updates on Education', 'column_list': [{'column_title': 'Education Policies', 'column_requirement': 'All contents must be related to recent education policies, reforms, and updates.', 'search_keywords': 'education policies reforms updates government school college university'}, {'column_title': 'Education Technology', 'column_requirement': 'Focus on the latest advancements in educational technology, online learning, and digital resources.', 'search_keywords': 'education technology online learning digital resources edtech'}, {'column_title': 'Education Research', 'column_requirement': 'Articles and studies on educational research, trends, and innovations.', 'search_keywords': 'education research trends innovations studies'}]}
> 2024-06-17 14:40:11,955 [INFO]  [Start Generate Column] Education Policies
> 2024-06-17 14:40:13,016 [INFO]  [Search News Count]     3
> [Request Data]
>  {
>     "stream": true,
>     "messages": [
>         {
>             "role": "user",
>             "content": "# [INPUT]:\n[{'id': 0, 'title': 'Malemu Saulos Chilima was part of the university team in support of the transition says Chikosa Silungwe', 'brief': 'Malemu Saulos Chilima \\xa0was part of the university team in support of the transition \\xa0says\\xa0 Chikosa Silungwe - The Maravi Post', 'url': 'https://www.maravipost.com/malemu-saulos-chilima-was-part-of-the-university-team-in-support-of-the-transition-says-chikosa-silungwe/', 'source': 'The Maravi Post', 'date': '2024-06-16T12:00:00+00:00'}, {'id': 1, 'title': 'Colleges and Schools at Purdue', 'brief': 'The Colleges and Schools at Purdue University have been dedicated to preparing students for a competitive job market. Please look through our academic catalog below to find the program that will help meet your career and life goals.', 'url': 'https://www.purdue.edu/home/colleges_schools/', 'source': 'Purdue University', 'date': '2024-06-16T06:52:00+00:00'}, {'id': 2, 'title': 'Malawi Catholic Church Criticizes Leadership Over Delayed Response to VP Saulos Chilima Plane Crash Rescue', 'brief': 'Malawi Catholic Church Criticizes Leadership Over Delayed Response to VP Saulos Chilima Plane Crash Rescue - The Maravi Post', 'url': 'https://www.maravipost.com/malawi-catholic-church-criticizes-leadership-over-delayed-response-to-vp-saulos-chilima-plane-crash-rescue/', 'source': 'The Maravi Post', 'date': '2024-06-16T17:31:00+00:00'}]\n\n# [INSTRUCTION]:\nnews select rules:\n- All contents must be related to recent education policies, reforms, and updates.\n- if several news are similar, just retain the one with most famous source and output\n  {can_use} as false for others\n\n\n# [OUTPUT REQUIREMENT]:\n## TYPE:\nJSON can be parsed in Python\n## FORMAT:\n[\n\t\n\t{\n\t\t\"id\": <int>,//value from {input.[].id}\n\t\t\"can_use\": <bool>,//judge if {input.brief} can be used according {instruct}\n\t\t\"recommend_comment\": <str>,//provide your recommend comment if {can_use} == true, or just output null\n\t\t},,\n\t\\\\...\n]\n\n\n[OUTPUT]:\n"
>         }
>     ],
>     "model": "gpt-35-turbo",
>     "temperature": 0.75
> }
> [Realtime Response]
> 
> [Request] OpenAI Error: {'id': '', 'choices': [], 'created': 0, 'model': '', 'object': '', 'system_fingerprint': None, 'usage': None, 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}]}
> 
> {
>         "id": 0,
>         "can_use": false,
>         "recommend_comment": null
> }
> 
> 
> --------------------------
> 
> [Final Reply]
>  
> {
>         "id": 0,
>         "can_use": false,
>         "recommend_comment": null
> }
> 
>          
> --------------------------
> 
> [Cleaned JSON String]:
>  {
>         "id": 0,
>         "can_use": false,
>         "recommend_comment": null
> }
> 
> --------------------------
> 
> 2024-06-17 14:40:20,449 - ERROR - Node Execution Exception: 'pick_news'(aa01827e-c3a4-4ace-9f9a-a9eb21b88133) string indices must be integers
> 2024-06-17 14:40:20,449 - ERROR - Node Execution Exception: 'generate_columns'(ab330942-ae88-4a79-a30c-c481602679b1) string indices must be integers
> Traceback (most recent call last):
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
>     exec_res = chunk_executor(deps_dict, self.store)
>   File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/column_workflow.py", line 54, in pick_news_executor
>     if pick_result["can_use"]:
> TypeError: string indices must be integers
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 266, in _exec_chunk_with_dep_core
>     exec_res = chunk_executor(deps_dict, self.store)
>   File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/main_workflow.py", line 58, in generate_columns_executor
>     column_data = start_column_workflow(
>   File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/column_workflow.py", line 153, in start
>     column_workflow.start()
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 67, in start
>     self.executor.start(runtime_data)
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
>     self._execute_main(entries)
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
>     self._execute_partial(
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
>     child_executed = self._execute_single_chunk(
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
>     self._execute_single_chunk_core(
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
>     exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
>     raise Exception(e)
> Exception: string indices must be integers
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/app.py", line 21, in <module>
>     main_workflow.start(
>   File "/Users/terry/Desktop/Azure/Agently-Daily-News-Collector/workflows/main_workflow.py", line 109, in start
>     main_workflow.start()
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/Workflow.py", line 67, in start
>     self.executor.start(runtime_data)
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 33, in start
>     self._execute_main(entries)
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 70, in _execute_main
>     self._execute_partial(
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 108, in _execute_partial
>     child_executed = self._execute_single_chunk(
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 165, in _execute_single_chunk
>     self._execute_single_chunk_core(
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 194, in _execute_single_chunk_core
>     exec_value = self._exec_chunk_with_dep_core(chunk, single_dep_map)
>   File "/Users/terry/miniconda3/envs/DailyNews/lib/python3.10/site-packages/Agently/Workflow/MainExecutor.py", line 270, in _exec_chunk_with_dep_core
>     raise Exception(e)
> Exception: string indices must be integers
> ```

I printed the `pick_results` variable, and found it to be a dictionary. The contents are :
`{'id': 0, 'can_use': True, 'recommend_comment': 'xxxxxxxxx.'} `

So, for the code `for pick_result in pick_results`, the first pick_result is `id`

**Comment by Maplemx** [comment]
Yes I see the problem, and I can see you're using AzureOpenAI.

This is a already-known issue that AzureOpenAI json format settings will always make mistakes when Agently tell it to generate list, it will force to transform list into one item dict. This is confirmed by many developers in community.

So we have to remove json format param in AzureOpenAI and OpenAI request and just use Agently prompt to generate list in next version(3.3.1.0).

The correct rate without setting json format will still be more than 90% according the test by community developers.
