### ISSUE TITLE
news duration set-Daily/Weekly/Bi-weekly/Monthly

### ISSUE THREAD

**Issue by Quickhl** [AgentEra/Agently-Daily-News-Collector#15]
To enable news duration to include a time band.
daily news is great, but mostly we are looking for weekly/monthly top news summary

The challenge must be the data scale.

**Comment by Quickhl** [comment]
yeah, I figured it out

**Comment by Maplemx** [comment]
updated in https://github.com/AgentEra/Agently-Daily-News-Collector/commit/1d1ef4c32eda9706f155a51002bc2a34610b9b0b
