### ISSUE TITLE
如何将输出的内容保存为 PDF 文件

### ISSUE THREAD

**Issue by godIsAProgrammer** [AgentEra/Agently-Daily-News-Collector#18]
在 examples 文件夹里面有 pdf 文件示例，但是在配置中和代码中没有找到相关内容，只有 md ，请问如何将生成的内容输出位 PDF 文件？

**Comment by Maplemx** [comment]
您可以下载一个MacDown或者类似的软件，使用它们提供的转pdf功能进行转换
