### ISSUE TITLE
China seems to be disconnected, may I ask how you solved it

### ISSUE THREAD

**Issue by yz-Python** [AgentEra/Agently-Daily-News-Collector#4]
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\duckduckgo_search\duckduckgo_search.py", line 104, in _get_url
    resp = self.client.request(method, url, params=params, content=content, data=data)
Exception: Error in request: error sending request for url (https://duckduckgo.com/): operation timed out

**Comment by Maplemx** [comment]
You can use proxy to solve firewall block issue.

Set your local proxy address like this in SETTINGS.yaml

<img width="748" alt="image" src="https://github.com/AgentEra/Agently-Daily-News-Collector/assets/4413155/af14bcb0-134a-4bc6-90b5-58a161532ca9">
